### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by Esemesek**
# Summary

* What issues does the pull request solve? Please tag them so that they will get automatically closed once the PR is merged
#7 
* What is the feature? (if applicable)
Adding unit tests
* How did you implement the solution?
Used `jest` library for writing unit tests 
* What areas of the library does it impact?
`helpers.js`

### What's required for testing (prerequisites)?
Ran `yarn` and `npm t`
image

@yeswanth I had to recreate this PR. I have added my changes on top of yours, and I think it is ready to go. Sorry for the inconvenience. I might have messed up a few git commands in a rush. Can you confirm this is OK?

### CODE REVIEW

**Comment by Esemesek** [comment]
@yeswanth Thank you for your first contribution <3

**Comment by yeswanth** [comment]
Hi @Esemesek, I'm just wondering why my name is not coming up in the GitHub contributors page after the PR got merged 🤔

**Comment by yeswanth** [comment]
I would also like to know more about not including negative test cases (as part of your commit). Would be helpful for me to learn why. Thanks :)

**Comment by Esemesek** [comment]
@yeswanth It might be because of squash. Sorry for that. I removed negative test cases, because they are covered by `flow` types.

**Pull request merged**
